-- V1__init.sql
-- Initial schema for AI PR Review Assistant (MySQL version)
-- All timestamps use DATETIME for timezone-aware storage
-- CHAR(36) for UUIDs (generated by application)

-- ============================================================
-- reviews — PR review task aggregate root
-- ============================================================
CREATE TABLE reviews (
    id                   CHAR(36)     PRIMARY KEY,
    repository           TEXT         NOT NULL,
    pr_number            INTEGER      NOT NULL,
    pr_head_sha          TEXT,
    pr_title             TEXT,
    pr_author            TEXT,
    status               VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    analysis_profile     VARCHAR(50)  NOT NULL DEFAULT 'STANDARD',
    requested_categories JSON,
    idempotency_key      VARCHAR(255),
    progress             DECIMAL(4,3) NOT NULL DEFAULT 0,
    files_total          INTEGER      NOT NULL DEFAULT 0,
    files_analyzed       INTEGER      NOT NULL DEFAULT 0,
    failure_reason       TEXT,
    callback_url         TEXT,
    submitted_by         VARCHAR(255),
    deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at           DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    started_at           DATETIME(6),
    completed_at         DATETIME(6),
    INDEX idx_reviews_repo_pr (repository(255), pr_number, created_at DESC),
    INDEX idx_reviews_active_status (status),
    INDEX idx_reviews_repo_sha (repository(255), pr_head_sha(255)),
    UNIQUE INDEX uq_reviews_idem_key (idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- change_summaries — PR change summary (1:1 with reviews)
-- ============================================================
CREATE TABLE change_summaries (
    id               CHAR(36)    PRIMARY KEY,
    review_id        CHAR(36)    NOT NULL UNIQUE,
    headline         TEXT        NOT NULL,
    inferred_purpose TEXT,
    primary_type     VARCHAR(50),
    affected_modules JSON,
    risk_highlights  JSON,
    payload          JSON,
    created_at       DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    INDEX idx_change_summaries_review (review_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- risk_items — identified risk findings
-- ============================================================
CREATE TABLE risk_items (
    id               CHAR(36)     PRIMARY KEY,
    review_id        CHAR(36)     NOT NULL,
    file_path        TEXT         NOT NULL,
    start_line       INTEGER,
    end_line         INTEGER,
    category         VARCHAR(100) NOT NULL,
    severity         VARCHAR(50)  NOT NULL,
    confidence       VARCHAR(50)  NOT NULL,
    confidence_score DECIMAL(4,3),
    detection_source VARCHAR(100) NOT NULL,
    rule_id          VARCHAR(255),
    pattern_key      VARCHAR(255),
    description      TEXT         NOT NULL,
    rationale        TEXT,
    code_snippet     TEXT,
    created_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    INDEX idx_risk_items_review (review_id),
    INDEX idx_risk_items_review_sev (review_id, severity, confidence),
    INDEX idx_risk_items_pattern (pattern_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- review_suggestions — actionable fix suggestions (1:1 with risk_items)
-- ============================================================
CREATE TABLE review_suggestions (
    id              CHAR(36)    PRIMARY KEY,
    risk_item_id    CHAR(36)    NOT NULL UNIQUE,
    explanation     TEXT        NOT NULL,
    recommendation  TEXT        NOT NULL,
    suggested_patch TEXT,
    `references`    JSON,
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (risk_item_id) REFERENCES risk_items(id) ON DELETE CASCADE,
    INDEX idx_suggestions_risk_item (risk_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- review_feedbacks — user feedback for calibration loop
-- ============================================================
CREATE TABLE review_feedbacks (
    id            CHAR(36)     PRIMARY KEY,
    risk_item_id  CHAR(36)     NOT NULL,
    review_id     CHAR(36)     NOT NULL,
    pattern_key   VARCHAR(255),
    verdict       VARCHAR(50)  NOT NULL,
    comment       TEXT,
    submitted_by  VARCHAR(255),
    created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (risk_item_id) REFERENCES risk_items(id) ON DELETE CASCADE,
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    INDEX idx_feedbacks_risk_item (risk_item_id),
    INDEX idx_feedbacks_pattern (pattern_key, verdict)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- feedback_calibrations — materialized calibration factors
-- ============================================================
CREATE TABLE feedback_calibrations (
    pattern_key        VARCHAR(255) PRIMARY KEY,
    accepted_count     INTEGER      NOT NULL DEFAULT 0,
    false_pos_count    INTEGER      NOT NULL DEFAULT 0,
    ignored_count      INTEGER      NOT NULL DEFAULT 0,
    calibration_factor DECIMAL(4,3) NOT NULL DEFAULT 1.000,
    updated_at         DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- analyzed_files — per-file analysis tracking
-- ============================================================
CREATE TABLE analyzed_files (
    id              CHAR(36)    PRIMARY KEY,
    review_id       CHAR(36)    NOT NULL,
    file_path       TEXT        NOT NULL,
    change_type     VARCHAR(50) NOT NULL,
    additions       INTEGER     NOT NULL DEFAULT 0,
    deletions       INTEGER     NOT NULL DEFAULT 0,
    analysis_status VARCHAR(50) NOT NULL,
    model_tier_used VARCHAR(50),
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    INDEX idx_analyzed_files_review (review_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- model_invocations — LLM call metering (cost/latency observability)
-- ============================================================
CREATE TABLE model_invocations (
    id                  CHAR(36)     PRIMARY KEY,
    review_id           CHAR(36),
    task_type           VARCHAR(100) NOT NULL,
    model_tier          VARCHAR(50)  NOT NULL,
    provider            VARCHAR(50)  NOT NULL,
    model_name          VARCHAR(100) NOT NULL,
    prompt_tokens       INTEGER      NOT NULL DEFAULT 0,
    completion_tokens   INTEGER      NOT NULL DEFAULT 0,
    total_tokens        INTEGER      NOT NULL DEFAULT 0,
    latency_ms          INTEGER,
    estimated_cost_usd  DECIMAL(10,5),
    outcome             VARCHAR(50)  NOT NULL,
    created_at          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    INDEX idx_model_inv_review (review_id),
    INDEX idx_model_inv_cost (created_at, provider, model_tier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
